---
# Include generate_ssl_key.yml tasks if generate_ssl_key is true
- name: Generate SSL keys
  delegate_to: localhost
  include_tasks: generate_ssl_key.yml
  tags: [generate_ssl_key]

# Include generate_ssl_key.yml tasks if generate_ssl_key is true
- name: Encrypt ZFS key
  delegate_to: localhost
  include_tasks: generate_encrypted_key.yml
  tags: [generate_encrypted_key]

# Ensure pip is installed with apt
- name: Ensure pip is installed with apt
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes

# Install the required Python packages
- name: Install required Python packages
  ansible.builtin.pip:
    name:
      - zfskeyprovider
    state: present

# Install zfskeyprovider service template
- name: Install zfskeyprovider service template
  ansible.builtin.template:
    src: zfskeyprovider.service.j2
    dest: /etc/systemd/system/zfskeyprovider.service

# Reload systemd daemon
- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

# Enable and start zfskeyprovider
- name: Restart zfskeyprovider
  systemd:
    name: zfskeyprovider
    state: restarted
    enabled: yes

# Upload the encrypted key to the zfskeyprovider service
- name: Post request to zfskeyprovider service
  ansible.builtin.uri:
    url: "http://{{ ansible_host }}:{{ zfskeyprovider.port }}/set_password"
    method: POST
    body: "user_input={{ lookup('file', 'encrypted.b64') | urlencode }}"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  tags: [upload_encrypted_key]

# Install zfs-load-key service template
- name: Install zfs-load-key service template
  ansible.builtin.template:
    src: zfs-load-key.service.j2
    dest: /etc/systemd/system/zfs-load-key.service
  notify:
    - Reload systemd daemon
    - Enable zfs-load-key
  when: vzekey_primary == True

- name: Upload private ssl key if primary
  ansible.builtin.copy:
    src: "{{ zfskeyprovider.private_local_ssl_path }}"
    dest: "{{ zfskeyprovider.private_ssl_path }}"
    owner: root
    group: root
    mode: '0600'
  when: vzekey_primary == True
